package be.pxl.collections.opdracht2;

public enum Action {
    MOVELEFTFOOTFORWARD, MOVERIGHTFOOTFORWARD, MOVELEFTFOOTBACKWARDS, MOVERIGHTFOOTBACKWARDS, RAISELEFTARM,
    RAISERIGHTARM, LOWERLEFTARM, LOWERRIGHTARM, TURNLEFT, TURNRIGHT, TURNHEADLEFT, TURNHEADRIGHT, TURNHEADTOMIDDLE,
    GRABITEM, DROPITEM, POWERDOWN, POWERUP, SYSTEMCHECK, IDLE;
}
